package biz

import (
	"cron/internal/basic/conv"
	"fmt"
	"testing"
)

func TestReceiveTapd(t *testing.T) {

	str := `{
    "auto_task_id": "1155358509001000001",
    "auto_task_branch_id": "1155358509001000012",
    "workspace_id": "55358509",
    "search": null,
    "event": {
        "workspace_id": "55358509",
        "user": "王**",
        "object_type": "bug",
        "id": "1155358509001031184",
        "timestamp": 1724661810,
        "timestamp_micro": 1724661810181,
        "new": {
            "current_owner": "王**;",
            "flows": "new|in_progress|resolved|verified|reopened|in_progress|resolved|verified",
            "id": "1155358509001031184",
            "lastmodify": "王**",
            "modified": "2024-08-26 16:43:29",
            "status": "verified",
            "verify_time": "2024-08-26 16:43:29"
        },
        "old": {
            "current_owner": "刘**;",
            "flows": "new|in_progress|resolved|verified|reopened|in_progress|resolved",
            "id": "1155358509001031184",
            "lastmodify": "刘**",
            "modified": "2024-08-26 16:43:28",
            "status": "resolved",
            "verify_time": null
        },
        "object_info": {
            "assigned_time": null,
            "audit_time": null,
            "auditer": null,
            "baseline_close": "",
            "baseline_find": "",
            "baseline_join": "",
            "baseline_test": "",
            "begin": null,
            "bugtype": "",
            "cc": null,
            "closed": null,
            "closer": null,
            "confirmer": null,
            "created": "2024-08-26 16:38:34",
            "created_from": null,
            "current_owner": "王**;",
            "custom_field_10": "",
            "custom_field_100": "",
            "custom_field_101": "",
            "custom_field_102": "",
            "custom_field_103": "",
            "custom_field_104": "",
            "custom_field_105": "",
            "custom_field_106": "",
            "custom_field_107": "",
            "custom_field_108": "",
            "custom_field_109": "",
            "custom_field_11": "",
            "custom_field_110": "",
            "custom_field_111": "",
            "custom_field_112": "",
            "custom_field_113": "",
            "custom_field_114": "",
            "custom_field_115": "",
            "custom_field_116": "",
            "custom_field_117": "",
            "custom_field_118": "",
            "custom_field_119": "",
            "custom_field_12": "",
            "custom_field_120": "",
            "custom_field_121": "",
            "custom_field_122": "",
            "custom_field_123": "",
            "custom_field_124": "",
            "custom_field_125": "",
            "custom_field_126": "",
            "custom_field_127": "",
            "custom_field_128": "",
            "custom_field_129": "",
            "custom_field_13": "",
            "custom_field_130": "",
            "custom_field_131": "",
            "custom_field_132": "",
            "custom_field_133": "",
            "custom_field_134": "",
            "custom_field_135": "",
            "custom_field_136": "",
            "custom_field_137": "",
            "custom_field_138": "",
            "custom_field_139": "",
            "custom_field_14": "",
            "custom_field_140": "",
            "custom_field_141": "",
            "custom_field_142": "",
            "custom_field_143": "",
            "custom_field_144": "",
            "custom_field_145": "",
            "custom_field_146": "",
            "custom_field_147": "",
            "custom_field_148": "",
            "custom_field_149": "",
            "custom_field_15": "",
            "custom_field_150": "",
            "custom_field_151": "",
            "custom_field_152": "",
            "custom_field_153": "",
            "custom_field_154": "",
            "custom_field_155": "",
            "custom_field_156": "",
            "custom_field_157": "",
            "custom_field_158": "",
            "custom_field_159": "",
            "custom_field_16": "",
            "custom_field_160": "",
            "custom_field_161": "",
            "custom_field_162": "",
            "custom_field_163": "",
            "custom_field_164": "",
            "custom_field_165": "",
            "custom_field_166": "",
            "custom_field_167": "",
            "custom_field_168": "",
            "custom_field_169": "",
            "custom_field_17": "",
            "custom_field_170": "",
            "custom_field_171": "",
            "custom_field_172": "",
            "custom_field_173": "",
            "custom_field_174": "",
            "custom_field_175": "",
            "custom_field_176": "",
            "custom_field_177": "",
            "custom_field_178": "",
            "custom_field_179": "",
            "custom_field_18": "",
            "custom_field_180": "",
            "custom_field_181": "",
            "custom_field_182": "",
            "custom_field_183": "",
            "custom_field_184": "",
            "custom_field_185": "",
            "custom_field_186": "",
            "custom_field_187": "",
            "custom_field_188": "",
            "custom_field_189": "",
            "custom_field_19": "",
            "custom_field_190": "",
            "custom_field_191": "",
            "custom_field_192": "",
            "custom_field_193": "",
            "custom_field_194": "",
            "custom_field_195": "",
            "custom_field_196": "",
            "custom_field_197": "",
            "custom_field_198": "",
            "custom_field_199": "",
            "custom_field_20": "",
            "custom_field_200": "",
            "custom_field_21": "",
            "custom_field_22": "",
            "custom_field_23": "",
            "custom_field_24": "",
            "custom_field_25": "",
            "custom_field_26": "",
            "custom_field_27": "",
            "custom_field_28": "",
            "custom_field_29": "",
            "custom_field_30": "",
            "custom_field_31": "",
            "custom_field_32": "",
            "custom_field_33": "",
            "custom_field_34": "",
            "custom_field_35": "",
            "custom_field_36": "",
            "custom_field_37": "",
            "custom_field_38": "",
            "custom_field_39": "",
            "custom_field_40": "",
            "custom_field_41": "",
            "custom_field_42": "",
            "custom_field_43": "",
            "custom_field_44": "",
            "custom_field_45": "",
            "custom_field_46": "",
            "custom_field_47": "",
            "custom_field_48": "",
            "custom_field_49": "",
            "custom_field_50": "",
            "custom_field_51": "",
            "custom_field_52": "",
            "custom_field_53": "",
            "custom_field_54": "",
            "custom_field_55": "",
            "custom_field_56": "",
            "custom_field_57": "",
            "custom_field_58": "",
            "custom_field_59": "",
            "custom_field_6": "",
            "custom_field_60": "",
            "custom_field_61": "",
            "custom_field_62": "",
            "custom_field_63": "",
            "custom_field_64": "",
            "custom_field_65": "",
            "custom_field_66": "",
            "custom_field_67": "",
            "custom_field_68": "",
            "custom_field_69": "",
            "custom_field_7": "",
            "custom_field_70": "",
            "custom_field_71": "",
            "custom_field_72": "",
            "custom_field_73": "",
            "custom_field_74": "",
            "custom_field_75": "",
            "custom_field_76": "",
            "custom_field_77": "",
            "custom_field_78": "",
            "custom_field_79": "",
            "custom_field_8": "",
            "custom_field_80": "",
            "custom_field_81": "",
            "custom_field_82": "",
            "custom_field_83": "",
            "custom_field_84": "",
            "custom_field_85": "",
            "custom_field_86": "",
            "custom_field_87": "",
            "custom_field_88": "",
            "custom_field_89": "",
            "custom_field_9": "",
            "custom_field_90": "",
            "custom_field_91": "",
            "custom_field_92": "",
            "custom_field_93": "",
            "custom_field_94": "",
            "custom_field_95": "",
            "custom_field_96": "",
            "custom_field_97": "",
            "custom_field_98": "",
            "custom_field_99": "",
            "custom_field_five": "https://gitee.com/project1/item1/pulls/504       https://gitee.com/project2/item2/pulls/160 https://gitee.com/project3/item3/pulls/1006",
            "custom_field_four": "project1/hotfix/240823    \n    project2/hotfix/240823  project3/feature/sm0810{stock,order}",
            "custom_field_one": "",
            "custom_field_three": "",
            "custom_field_two": "历史缺陷",
            "custom_plan_field_1": "0",
            "custom_plan_field_10": "0",
            "custom_plan_field_2": "0",
            "custom_plan_field_3": "0",
            "custom_plan_field_4": "0",
            "custom_plan_field_5": "0",
            "custom_plan_field_6": "0",
            "custom_plan_field_7": "0",
            "custom_plan_field_8": "0",
            "custom_plan_field_9": "0",
            "de": "王**;",
            "deadline": null,
            "delayed": "0",
            "description": "<p>***<\/p>",
            "description_type": "1",
            "due": null,
            "effort": null,
            "effort_completed": "0",
            "estimate": null,
            "exceed": "0",
            "feature": null,
            "fixer": "王**",
            "flows": "new|in_progress|resolved|verified|reopened|in_progress|resolved|verified",
            "follower": "",
            "frequency": "",
            "id": "1155358509001031184",
            "in_progress_time": "2024-08-26 16:43:15",
            "issue_id": null,
            "iteration_id": "0",
            "label": null,
            "lastmodify": "王**",
            "markdown_description": null,
            "milestone": null,
            "modified": "2024-08-26 16:43:29",
            "module": "ERP",
            "originphase": "",
            "os": "",
            "parent_id": null,
            "participator": "王**;刘**",
            "platform": "",
            "priority": "insignificant",
            "progress": "0",
            "project_id": "55358509",
            "regression_number": "1",
            "reject_time": null,
            "release_id": null,
            "remain": "0",
            "reopen_time": "2024-08-26 16:43:02",
            "reporter": "王**",
            "resolution": "fixed",
            "resolved": "2024-08-26 16:43:22",
            "severity": "",
            "sid": "0",
            "size": null,
            "source": "",
            "sourcephase": "",
            "status": "verified",
            "story_id": null,
            "support_forum_id": null,
            "support_id": null,
            "suspend_time": null,
            "sync_type": "",
            "te": "",
            "template_id": "1155358509001000039",
            "testmode": "",
            "testphase": "",
            "testtype": "",
            "ticket_id": null,
            "title": "test",
            "verify_time": "2024-08-26 16:43:29",
            "version_close": "",
            "version_fix": "",
            "version_report": "",
            "version_test": ""
        },
        "event_key": "bug::status_change",
        "from": "web",
        "event_id": "7ecdd3bb6f304beb3cc5de7124661770_17_a732bac3b433"
    }
}`
	p := map[string]any{
		"request": str,
	}
	temp := `[[$data := json_decode .request]]
[[$project := slice_filter (str_split $data.event.object_info.custom_field_four " ") "^\\s*$"]]
[[$pr := slice_filter (str_split $data.event.object_info.custom_field_five " ") "^\\s*$"]]
[[$related_user := slice_filter (str_split (printf "%s;%s;%s" $data.event.user $data.event.object_info.fixer $data.event.object_info.te) ";") "^\\s*$"]]
[[$dataset := make "[]map[string]string"]]

[[range $pr]]
	[[$dataset = append $dataset (slice_combine (str_find . "https://gitee.com/(.+)/([^/]+)/pulls/(\\d+)") "" "owner" "repo" "number" "type:pr")]]
[[end]]
[[range $project]]
	[[$temp_list := map_split (slice_combine (str_find . "([^/]+)(?:.*)(?:/|\\{(.*)\\})") "" "repo" "service" "type:jenkins") "," "service"]]
	[[range $temp_list]]
		[[$dataset = append $dataset .]]
	[[end]]
[[end]]

{
	"type": "[[$data.event.object_type]]",
	"event": "[[$data.event.event_key]]",
	"project": [[json_encode $project]],
	"pr": [[json_encode $pr]],

	"title": "[[$data.event.object_info.title]]",
	"html_url": "[[printf "https://www.tapd.cn/%s/bugtrace/bugs/view/%s" $data.event.workspace_id $data.event.id]]",
	"related_user_names": [[json_encode $related_user]],
	"dataset": [[json_encode $dataset]]
}`
	b, e := conv.DefaultStringTemplate().SetParam(p).Execute([]byte(temp))
	if e != nil {
		t.Fatal(e)
	}
	fmt.Println(string(b))
}

func TestName(t *testing.T) {
	a := dtos.ReceiveWebHook{
		RelatedUserNames: []string{"a", "b"},
	}

	r := &dtos.MsgPushRequest{
		Args: map[string]any{
			"receive": map[string]any{
				"user_names": a.RelatedUserNames,
			},
		},
	}
	//userAppend := []*models.CronUser{}
	if temp, ok := r.Args["receive"].(map[string]any); ok {
		if names, ok := temp["user_names"].([]string); ok && len(names) > 0 {
			fmt.Println("ok", names)
		}
	}
}
